version: '3.8'

services:
  web:
    build: .
    ports:
      - 5000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./:/usr/src/
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A worker beat --loglevel=info
    volumes:
      - ./:/usr/src/
    env_file:
      - .env
    depends_on:
      - web
      - redis 

  celery-worker:
    build: .
    command: celery -A worker worker
    volumes:
      - ./:/usr/src/
    env_file:
      - .env
    depends_on:
      - web
      - redis
  redis:
    image: redis:6-alpine

volumes:
  db-data: